[theme]
base = "dark"
primaryColor = "#22c55e"
backgroundColor = "#020617"
secondaryBackgroundColor = "#020617"
textColor = "#f9fafb"
font = "sans serif"

[server]
headless = true

[client]
toolbarMode = "minimal"
